#### Importing data

In [2]:
import pandas as pd


df = pd.read_csv('input_data.txt', sep='\t')

df

,standard_sort,unit_id,parent_unit_id,unit_name,rank,start_age_ma,end_age_ma,start_age_err_ma,font_color,cmyk,cyan,magenta,yellow,black,rgb,red,green,blue,html_rgb_hash
0,1,194,92.0,Meghalayan,Stage,0,0.0042,NaN,Black,0/10/5/0,0,10,5,0,253/237/236,253,237,236,#FDEDEC
1,2,92,81.0,Upper/Late Holocene,Subseries,NaN,NaN,NaN,Black,0/10/5/0,0,10,5,0,253/237/236,253,237,236,#FDEDEC
2,3,193,91.0,Northgrippian,Stage,0.0042,0.0082,NaN,Black,0/10/10/0,0,10,10,0,253/236/228,253,236,228,#FDECE4
3,4,91,81.0,Middle Holocene,Subseries,NaN,NaN,NaN,Black,0/10/10/0,0,10,10,0,253/236/228,253,236,228,#FDECE4
4,5,192,90.0,Greenlandian,Stage,0.0082,0.0117,NaN,Black,0/10/15/0,0,10,15,0,254/236/219,254,236,219,#FEECDB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,190,16,3.0,unnamed4,System,3600,4031 ± 3,NaN,NaN,5/90/0/0,5,90,0,0,230/29/140,230,29,140,#E61D8C
190,191,6,3.0,Eoarchean,Erathem,3600,4031 ± 3,NaN,Black,10/100/0/0,10,100,0,0,218/3/127,218,3,127,#DA037F
191,192,3,1.0,Archean,Eonothem,2500,4031 ± 3,NaN,Black,0/100/0/0,0,100,0,0,240/4/127,240,4,127,#F0047F
192,193,2,1.0,Hadean,Eonothem,4031 ± 3,4567,NaN,White,30/100/0/0,30,100,0,0,174/2/126,174,2,126,#AE027E
193,194,1,NaN,Precambrian,super-Eonothem,NaN,NaN,NaN,Black,0/75/30/0,0,75,30,0,247/67/112,247,67,112,#F74370

#### Creating ranks table

In [2]:
ranks = df['rank'].unique()[::-1]
ranks_df = pd.DataFrame({'rank': ranks},
                        index=range(1, len(ranks)+1))
ranks_df.to_csv('strat_ranks.txt', index_label = 'rank_id')
ranks_df

             rank
1  super-Eonothem
2        Eonothem
3       Subsystem
4         Erathem
5          System
6          Series
7       Subseries
8           Stage

#### Crating data sources table

In [3]:
sources = ['ChronostratChart2023-09']
data_sources_df = pd.DataFrame({'source_name': sources,},
                               index=range(1, len(sources)+1))
data_sources_df.to_csv('strat_data_sources.txt', index_label = 'source_id')
data_sources_df

               source_name
1  ChronostratChart2023-09

#### Creating units table

In [41]:
from decimal import Decimal

df['source_id'] = 1
strat_units_df = df[['unit_id',
                    'parent_unit_id',
                    'unit_name',
                    'start_age_ma',
                    'end_age_ma',
                    'start_age_err_ma',
                    'font_color',
                    'cmyk',
                    'cyan',
                    'magenta',
                    'yellow',
                    'black',
                    'rgb',
                    'red',
                    'green',
                    'blue',
                    'html_rgb_hash',
                    'source_id',
                    'standard_sort']].copy()

strat_units_df['parent_unit_id'] = strat_units_df['parent_unit_id'].fillna(-1).apply(int)
strat_units_df['start_age_err_ma'] = strat_units_df['start_age_ma'].apply(
    lambda x: Decimal(str(x).replace('~ ', '').split('±')[1]) if pd.notna(x) and '±' in str(x) else None)

strat_units_df['start_age_ma'] = strat_units_df['start_age_ma'].apply(
     lambda x: Decimal(str(x).replace('~ ', '').split('±')[0]) if pd.notna(x) else x)
strat_units_df['end_age_ma'] = strat_units_df['end_age_ma'].apply(
     lambda x: Decimal(str(x).replace('~ ', '').split('±')[0]) if pd.notna(x) else x)

# strat_units_df['start_age_ma'].unique()

strat_units_df.to_csv('strat_units.txt', index=False)
strat_units_df.head(60)

,unit_id,parent_unit_id,unit_name,start_age_ma,end_age_ma,start_age_err_ma,font_color,cmyk,cyan,magenta,yellow,black,rgb,red,green,blue,html_rgb_hash,source_id,standard_sort
0,194,92,Meghalayan,0,0.0042,None,Black,0/10/5/0,0,10,5,0,253/237/236,253,237,236,#FDEDEC,1,1
1,92,81,Upper/Late Holocene,NaN,NaN,None,Black,0/10/5/0,0,10,5,0,253/237/236,253,237,236,#FDEDEC,1,2
2,193,91,Northgrippian,0.0042,0.0082,None,Black,0/10/10/0,0,10,10,0,253/236/228,253,236,228,#FDECE4,1,3
3,91,81,Middle Holocene,NaN,NaN,None,Black,0/10/10/0,0,10,10,0,253/236/228,253,236,228,#FDECE4,1,4
4,192,90,Greenlandian,0.0082,0.0117,None,Black,0/10/15/0,0,10,15,0,254/236/219,254,236,219,#FEECDB,1,5
5,90,81,Lower/Early Holocene,NaN,NaN,None,Black,0/10/15/0,0,10,15,0,254/236/219,254,236,219,#FEECDB,1,6
6,81,41,Holocene,NaN,NaN,None,Black,0/10/20/0,0,10,20,0,254/235/210,254,235,210,#FEEBD2,1,7
7,191,89,Upper Pleistocene,0.0117,0.129,None,Black,0/5/15/0,0,5,15,0,255/242/211,255,242,211,#FFF2D3,1,8
8,89,80,Upper/Late Pleistocene,NaN,NaN,None,Black,0/5/15/0,0,5,15,0,255/242/211,255,242,211,#FFF2D3,1,9
9,190,88,Chibanian,0.129,0.774,None,Black,0/5/20/0,0,5,20,0,255/242/199,255,242,199,#FFF2C7,1,10
10,88,80,Middle Pleistocene,NaN,NaN,None,Black,0/5/20/0,0,5,20,0,255/242/199,255,242,199,#FFF2C7,1,11
11,189,87,Calabrian,0.774,1.8,None,Black,0/5/25/0,0,5,25,0,255/242/186,255,242,186,#FFF2BA,1,12
12,188,87,Gelasian,1.8,2.58,None,Black,0/5/30/0,0,5,30,0,255/237/179,255,237,179,#FFEDB3,1,13
13,87,80,Lower/Early Pleistocene,NaN,NaN,None,Black,0/5/35/0,0,5,35,0,255/240/185,255,240,185,#FFF0B9,1,14
14,80,41,Pleistocene,NaN,NaN,None,Black,0/5/40/0,0,5,40,0,255/239/175,255,239,175,#FFEFAF,1,15
15,41,15,Quaternary,NaN,NaN,None,Black,0/0/50/0,0,0,50,0,249/249/127,249,249,127,#F9F97F,1,16
16,187,86,Piacenzian,2.58,3.6,None,Black,0/0/25/0,0,0,25,0,255/255/191,255,255,191,#FFFFBF,1,17
17,86,79,Upper/Late Pliocene,NaN,NaN,None,Black,0/5/25/0,0,5,25,0,255/242/205,255,242,205,#FFF2CD,1,18
18,186,85,Zanclean,3.6,5.333,None,Black,0/0/30/0,0,0,30,0,255/255/179,255,255,179,#FFFFB3,1,19
19,85,79,Lower/Early Pliocene,NaN,NaN,None,Black,0/5/30/0,0,5,30,0,255/242/195,255,242,195,#FFF2C3,1,20
20,79,40,Pliocene,NaN,NaN,None,Black,0/0/40/0,0,0,40,0,255/255/153,255,255,153,#FFFF99,1,21
21,185,84,Messinian,5.333,7.246,None,Black,0/0/55/0,0,0,55,0,255/255/115,255,255,115,#FFFF73,1,22
22,184,84,Tortonian,7.246,11.63,None,Black,0/0/60/0,0,0,60,0,255/255/102,255,255,102,#FFFF66,1,23
23,84,78,Upper/Late Miocene,NaN,NaN,None,Black,0/5/55/0,0,5,55,0,255/236/140,255,236,140,#FFEC8C,1,24
24,183,83,Serravallian,11.63,13.82,None,Black,0/0/65/0,0,0,65,0,255/255/89,255,255,89,#FFFF59,1,25
25,182,83,Langhian,13.82,15.98,None,Black,0/0/70/0,0,0,70,0,255/255/77,255,255,77,#FFFF4D,1,26
26,83,78,Middle Miocene,NaN,NaN,None,Black,0/5/65/0,0,5,65,0,255/236/115,255,236,115,#FFEC73,1,27
27,181,82,Burdigalian,15.98,20.44,None,Black,0/0/75/0,0,0,75,0,255/255/65,255,255,65,#FFFF41,1,28
28,180,82,Aquitanian,20.44,23.03,None,Black,0/0/80/0,0,0,80,0,255/255/51,255,255,51,#FFFF33,1,29
29,82,78,Lower/Early Miocene,NaN,NaN,None,Black,0/5/75/0,0,5,75,0,255/236/85,255,236,85,#FFEC55,1,30
30,78,40,Miocene,NaN,NaN,None,Black,0/0/100/0,0,0,100,0,255/255/0,255,255,0,#FFFF00,1,31
31,40,15,Neogene,NaN,NaN,None,Black,0/10/90/0,0,10,90,0,255/230/25,255,230,25,#FFE619,1,32
32,179,77,Chattian,23.03,27.82,None,Black,0/10/30/0,0,10,30,0,254/230/170,254,230,170,#FEE6AA,1,33
33,178,77,Rupelian,27.82,33.9,None,Black,0/15/35/0,0,15,35,0,254/217/154,254,217,154,#FED99A,1,34
34,77,39,Oligocene,NaN,NaN,None,Black,0/25/45/0,0,25,45,0,254/192/122,254,192,122,#FEC07A,1,35
35,177,76,Priabonian,33.9,37.71,None,Black,0/20/30/0,0,20,30,0,253/205/161,253,205,161,#FDCDA1,1,36
36,176,76,Bartonian,37.71,41.2,None,Black,0/25/35/0,0,25,35,0,253/192/145,253,192,145,#FDC091,1,37
37,175,76,Lutetian,41.2,47.8,None,Black,0/30/40/0,0,30,40,0,253/180/130,253,180,130,#FDB482,1,38
38,174,76,Ypresian,47.8,56,None,Black,0/35/45/0,0,35,45,0,252/167/115,252,167,115,#FCA773,1,39
39,76,39,Eocene,NaN,NaN,None,Black,0/30/50/0,0,30,50,0,253/180/108,253,180,108,#FDB46C,1,40
40,173,75,Thanetian,56,59.2,None,Black,0/25/50/0,0,25,50,0,253/191/111,253,191,111,#FDBF6F,1,41
41,172,75,Selandian,59.2,61.6,None,Black,0/25/55/0,0,25,55,0,254/191/101,254,191,101,#FEBF65,1,42
42,171,75,Danian,61.6,66,None,Black,0/30/55/0,0,30,55,0,253/180/98,253,180,98,#FDB462,1,43
43,75,39,Paleocene,NaN,NaN,None,Black,0/40/60/0,0,40,60,0,253/167/95,253,167,95,#FDA75F,1,44
44,39,15,Paleogene,NaN,NaN,None,Black,5/0/90/0,5,0,90,0,253/154/82,253,154,82,#FD9A52,1,45
45,15,5,Cenozoic,NaN,NaN,None,Black,40/0/5/0,40,0,5,0,242/249/29,242,249,29,#F2F91D,1,46
46,170,74,Maastrichtian,66,72.1,None,Black,5/0/45/0,5,0,45,0,242/250/140,242,250,140,#F2FA8C,1,47
47,169,74,Campanian,72.1,83.6,0.2,Black,10/0/50/0,10,0,50,0,230/244/127,230,244,127,#E6F47F,1,48
48,168,74,Santonian,83.6,86.3,0.2,Black,15/0/55/0,15,0,55,0,217/239/116,217,239,116,#D9EF74,1,49
49,167,74,Coniacian,86.3,89.8,0.5,Black,20/0/60/0,20,0,60,0,204/233/104,204,233,104,#CCE968,1,50
50,166,74,Turonian,89.8,93.9,0.3,Black,25/0/65/0,25,0,65,0,191/227/93,191,227,93,#BFE35D,1,51
51,165,74,Cenomanian,93.9,100.5,None,Black,30/0/70/0,30,0,70,0,179/222/83,179,222,83,#B3DE53,1,52
52,74,38,Upper Cretaceous,NaN,NaN,None,Black,35/0/75/0,35,0,75,0,166/216/74,166,216,74,#A6D84A,1,53
53,164,73,Albian,100.5,113.0,None,Black,20/0/40/0,20,0,40,0,204/234/151,204,234,151,#CCEA97,1,54
54,163,73,Aptian,113.0,121.4,None,Black,25/0/45/0,25,0,45,0,191/228/138,191,228,138,#BFE48A,1,55
55,162,73,Barremian,121.4,125.77,None,Black,30/0/50/0,30,0,50,0,179/223/127,179,223,127,#B3DF7F,1,56
56,161,73,Hauterivian,125.77,132.6,None,Black,35/0/55/0,35,0,55,0,166/217/117,166,217,117,#A6D975,1,57
57,160,73,Valanginian,132.6,139.8,None,Black,40/0/60/0,40,0,60,0,153/211/106,153,211,106,#99D36A,1,58
58,159,73,Berriasian,139.8,145.0,None,Black,45/0/65/0,45,0,65,0,140/205/96,140,205,96,#8CCD60,1,59
59,73,38,Lower Cretaceous,NaN,NaN,None,Black,45/0/70/0,45,0,70,0,140/205/87,140,205,87,#8CCD57,1,60

In [43]:
pip install jupyterlab-csv

ERROR: Could not find a version that satisfies the requirement jupyterlab-csv (from versions: none)
ERROR: No matching distribution found for jupyterlab-csv
Note: you may need to restart the kernel to use updated packages.